# Generated by Django 4.1.6 on 2023-03-01 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='howManyLike',
            field=models.ManyToManyField(blank=True, default=None, related_name='howManyLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='mainlikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainint', models.CharField(default='Like', max_length=5)),
                ('mainPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.post')),
                ('mainUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
