# Generated by Django 4.1.7 on 2023-03-01 08:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateModifies',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
