# Generated by Django 4.1.6 on 2023-03-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_post_howmanylike_mainlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=100)),
                ('main_body', models.TextField()),
                ('main_date', models.DateTimeField(auto_now_add=True)),
                ('main_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comments', to='stream.post')),
            ],
        ),
    ]
