# Generated by Django 4.1.6 on 2023-03-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='main_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='main_name',
            new_name='name',
        ),
    ]
