# Generated by Django 4.1.7 on 2023-03-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_profile_datemodifies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dateModifies',
            new_name='dateModified',
        ),
    ]
