# Generated by Django 4.1.6 on 2023-03-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_rename_body_comment_main_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='main_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='main_name',
            new_name='name',
        ),
    ]
