# Generated by Django 4.1.7 on 2023-03-08 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0007_rename_main_body_comment_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='howManyLike',
            field=models.ManyToManyField(related_name='howManyLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
